### ISSUE TITLE
Room for an `Iter` package?

### ISSUE THREAD

**Issue by MartinBernstorff** [rustedpy/maybe#3]
Hi there @francium! I couldn't find your contact information, so I hope it's okay I write here.

Love your work on `Result` and `Maybe`! When working in Python, I've sorely missed `.into_iter()`, `.map()` etc. 

I've been at work on a package to solve that, [FunctionalPy](https://github.com/MartinBernstorff/FunctionalPy).

It's at an early alpha stage, and I'm strongly considering:
* Supporting Result/Maybe
* Renaming the package to `Iter`

I think the rustedpy org might be a good home for a package like that, and I'd gladly volunteer as maintainer. Any thoughts? :-)

**Comment by francium** [comment]
Yeah, sounds interesting. I don't see any issues with welcoming you and setting up a new repo you can be the maintainer of.

Would you like to transfer you existing repo or would you prefer I create a new repo, set you as a maintainer and you can push the code manually to the new repo?

**Comment by MartinBernstorff** [comment]
Sounds great! Transferring the existing repo seems like a good move. I'll use the package a bit more on my end to iron out superficial issues, then reach out 👍
